language: java

#for docker
sudo: required

jdk:
  - openjdk11

script:
  - mvn compile jib:build

#after_success:
#  # push application image to docker registry
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push agrcom/posessor-settelment-generator:latest;
#    fi

# support for docker
services:
  - docker